http:
  middlewares:
    hsts:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
    httptohttps:
      redirectscheme:
        scheme: https
        permanent: true
