api:
  dashboard: true
  debug: true
  insecure: true
core:
  defaultRuleSyntax: v2
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
      - "127.0.0.1/8"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
      - "127.0.0.1/8"
log:
  level: INFO
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: proxylampy
    watch: true
  file:
    filename: /etc/traefik/middlewares.yml
  swarm:
    network: proxylampy
tls:
  certificates:
  - certFile: /etc/ssl/traefik/cert.pem
    keyFile: /etc/ssl/traefik/privkey.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/traefik/cert.pem
        keyFile: /etc/ssl/traefik/privkey.pem
