api:
  dashboard: true
  debug: true
  insecure: true
core:
  defaultRuleSyntax: v2
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
log:
  level: DEBUG
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: true
  file:
    filename: /etc/traefik/tls.yml
  swarm:
    network: proxywebserver