name: ci
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install npm dependencies
        run: npm install
      - name: 'Docker swarm init'
        run: npm run docker:swarm-init
      - name: 'Create proxy network'
        run: npm run docker:create-network
      - name: 'Image pull'
        run: npm run docker:getpull-image
      - name: 'Build containers'
        run: npm run docker:deploy
      - name: 'sleep'
        run: npm run waiting:all
      - name: 'docker ls'
        run: npm run docker:ls
      - name: linter readme
        run: npm run lint:markdown
  exec:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install npm dependencies
        run: npm install
      - name: 'NPM EXEC'
        run: npm run exec